### PR TITLE
Revert "new line"

### PR DESCRIPTION
**Pull request by rdmorin**
This reverts commit 22b80a6.# Pull Request Checklists

**Important:** When opening a pull request, keep only the applicable checklist and delete all other sections.

### Required

- [X] I tested the new code for my use case (please provide a reproducible example of how you tested the new functionality)

- [X] I ensured all dplyr functions that commonly conflict with other packages are fully qualified. 

This can be checked and addressed by running `check_functions.pl` and responding to the prompts. Test your code _after_ you do this.

- [ ] I generated the documentation and checked for errors relating to the new function (e.g. `devtools::document()`) and added `NAMESPACE` and all other modified files in the root directory and under `man`. 

### Optional but preferred with PRs

- [ ] I updated and/or successfully knitted a vignette that relies on the modified code (which ones?)

### Required

- [ ] I documented my function using [ROxygen style](https://jozef.io/r102-addin-roxytags/#:~:text=Inserting%20a%20skeleton%20%2D%20Do%20this,Shift%2BAlt%2BR%20).)

- [ ] All parameters for the function are described in the documentation and the function has a decriptive title. 

Example:
```
#' Use GISTIC2.0 scores output to reproduce maftools::chromoplot with more flexibility
#'
#' @param scores output file scores.gistic from the run of GISTIC2.0
#' @param genes_to_label optional. Provide a data frame of genes to label (if mutated). The first 3 columns must contain chromosome, start, and end coordinates. Another required column must contain gene names and be named `gene`. (truncated for example)
#' @param cutoff optional. Used to determine which regions to color as aberrant. Must be float in the range [0-1]. (truncated for example)
```

- [ ] My function uses a library that isn't already a dependency of GAMBLR and I made the package aware of this dependency using the function documentation `import` statment. 

Example:
```
#' @return nothing
#' @export
#' @import tidyverse ggrepel
```

## Checklist for changes to existing code

- [X] I added/removed arguments to a function and updated documentation for all changed/new arguments

- [X] I tested the new code for compatability with existing functionality in the Master branch (please provide a reprex of how you tested the original functionality)

### CODE REVIEW

**Comment by rdmorin** [comment]
This PR includes an example of a bit of code that should be added to any function that attempts to load a local file. This should help provide a more useful error for users who are running GAMBLR remotely and have either not set up their config (or loaded it properly) or have forgotten to sync the data locally. The relevant chunk is below. Without this code, calling get_manta_sv() on a remote computer will fail with an error about a missing file. 

```
    #check for missingness
    if(!file.exists(sv_file)){
      message("Cannot find file locally. If working remotely, perhaps you forgot to load your config (see below) or sync your files?")
      message('Sys.setenv(R_CONFIG_ACTIVE= "remote"')
    }    #check for missingness
    if(!file.exists(sv_file)){
      message("Cannot find file locally. If working remotely, perhaps you forgot to load your config (see below) or sync your files?")
      message('Sys.setenv(R_CONFIG_ACTIVE= "remote"')
    }
```

**Comment by mattssca** [comment]
I have resolved the merge conflict. Nothing worth mentioning, just some blank lines.

**Comment by rdmorin** [comment]
I didn't realize this PR hadn't been merged. I've added to it. Can the new commits be reviewed please?

**Review by Kdreval — APPROVED** [review]
Thanks!

**Pull request merged**
