### PR TITLE
Transforming GAMBLR to a universe

### PR DESCRIPTION
**Pull request by Kdreval**
Formalizing the split into designated repos

### CODE REVIEW

**Comment by vladimirsouza** [comment]
If GAMBLR.results is installed, `library(GAMBLR)` gives you functions from GAMBLR.results instead of GAMBLR.data (nice!).
```
library(GAMBLR)

environmentName(environment(get_gambl_metadata))
# [1] "GAMBLR.results"

sessionInfo()
# ...
# other attached packages:
# [1] GAMBLR.results_0.1.0 GAMBLR.viz_0.1.0     GAMBLR.utils_0.1.0   GAMBLR.helpers_0.1.0
# [5] GAMBLR.data_0.1      GAMBLR_1.1          
# ...
```

If GAMBLR.results is not installed, you get functions from GAMBLR.data (super nice!). However, it shows an error message.
```
remove.packages("GAMBLR.results")

library(GAMBLR)
# Error: package or namespace load failed for ‘GAMBLR’:
#   .onAttach failed in attachNamespace() for 'GAMBLR', details:
#   call: library(pkg, lib.loc = loc, character.only = TRUE, warn.conflicts = FALSE)
# error: there is no package called ‘GAMBLR.results’

environmentName(environment(get_gambl_metadata))
# [1] "GAMBLR.data"
```
Also, when GAMBLR.results is not installed, GAMBLR.viz is not loaded. 
```
sessionInfo()
# ...
# other attached packages:
# [1] GAMBLR.utils_0.1.0   GAMBLR.helpers_0.1.0 GAMBLR.data_0.1      GAMBLR_1.1          
# ...

ashm_multi_rainbow_plot
# Error: object 'ashm_multi_rainbow_plot' not found
```

**Comment by Kdreval** [comment]
Thanks Vladimir!
This package is intended for GSC users to 1) make the new setup backwards compatible with old scripts and 2) avoid repetition of calling multiple library() at the preamble of the new scripts. There won't be a scenario where GAMBLR.results is not installed 😄

**Comment by vladimirsouza** [comment]
Very good the new README!

**Comment by vladimirsouza** [comment]
What is the point of commit [cleanup: merge master and resolve conflicts](https://github.com/morinlab/GAMBLR/pull/250/commits/048334053bbd9e10ae2e16d2ebc7813628709b10)?

**Comment by vladimirsouza** [comment]
I got confused because when I clicked on that commit I got this
image

Then I clicked on "view the diff" and got this
image

So I didn't know what was the change.

**Comment by vladimirsouza** [comment]
Do you know why it's marked with a failing check?
Screenshot from 2024-01-26 15-56-41

**Comment by vladimirsouza** [comment]
I haven't tested installing the package again using this branch. Did you have the chance to try to install it?

**Comment by vladimirsouza** [comment]
I uninstalled all gamblr children (GAMBLR.results, GAMBLR.viz, GAMBLR.utils, GAMBLR.helpers, GAMBLR.data) and installed GAMBLR again, and everything went well.

**Comment by Kdreval** [comment]
The check is failing because `devtools::install()` changed the way it works, so none of the biocmanager packages are found and installed. Therefore the install fails since the dependencies are not deemed available. This branch contains the fix for this situation going forward, and it was tested on this branch, [here](https://github.com/morinlab/GAMBLR/actions/runs/6747816741/job/18344804867) is a relevant actions run.

**Pull request merged**
